// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/dta.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_dta_proto protoreflect.FileDescriptor

const file_api_proto_dta_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/dta.proto\x12\n" +
	"module.dta\x1a\x1cgoogle/protobuf/struct.proto2K\n" +
	"\n" +
	"DTAService\x12=\n" +
	"\aValidar\x12\x17.google.protobuf.Struct\x1a\x17.google.protobuf.Struct\"\x00B\x17Z\x15dta-service/api/protob\x06proto3"

var file_api_proto_dta_proto_goTypes = []any{
	(*structpb.Struct)(nil), // 0: google.protobuf.Struct
}
var file_api_proto_dta_proto_depIdxs = []int32{
	0, // 0: module.dta.DTAService.Validar:input_type -> google.protobuf.Struct
	0, // 1: module.dta.DTAService.Validar:output_type -> google.protobuf.Struct
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_dta_proto_init() }
func file_api_proto_dta_proto_init() {
	if File_api_proto_dta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dta_proto_rawDesc), len(file_api_proto_dta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_dta_proto_goTypes,
		DependencyIndexes: file_api_proto_dta_proto_depIdxs,
	}.Build()
	File_api_proto_dta_proto = out.File
	file_api_proto_dta_proto_goTypes = nil
	file_api_proto_dta_proto_depIdxs = nil
}
