// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: api/proto/dta.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DTAService_Validar_FullMethodName = "/module.dta.DTAService/Validar"
)

// DTAServiceClient is the client API for DTAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DTAServiceClient interface {
	Validar(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type dTAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDTAServiceClient(cc grpc.ClientConnInterface) DTAServiceClient {
	return &dTAServiceClient{cc}
}

func (c *dTAServiceClient) Validar(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, DTAService_Validar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DTAServiceServer is the server API for DTAService service.
// All implementations must embed UnimplementedDTAServiceServer
// for forward compatibility.
type DTAServiceServer interface {
	Validar(context.Context, *structpb.Struct) (*structpb.Struct, error)
	mustEmbedUnimplementedDTAServiceServer()
}

// UnimplementedDTAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDTAServiceServer struct{}

func (UnimplementedDTAServiceServer) Validar(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method Validar not implemented")
}
func (UnimplementedDTAServiceServer) mustEmbedUnimplementedDTAServiceServer() {}
func (UnimplementedDTAServiceServer) testEmbeddedByValue()                    {}

// UnsafeDTAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DTAServiceServer will
// result in compilation errors.
type UnsafeDTAServiceServer interface {
	mustEmbedUnimplementedDTAServiceServer()
}

func RegisterDTAServiceServer(s grpc.ServiceRegistrar, srv DTAServiceServer) {
	// If the following call panics, it indicates UnimplementedDTAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DTAService_ServiceDesc, srv)
}

func _DTAService_Validar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DTAServiceServer).Validar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DTAService_Validar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DTAServiceServer).Validar(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

// DTAService_ServiceDesc is the grpc.ServiceDesc for DTAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DTAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "module.dta.DTAService",
	HandlerType: (*DTAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validar",
			Handler:    _DTAService_Validar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/dta.proto",
}
