// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/desistimiento.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DesistimientoService_Desistimiento_FullMethodName = "/apigrpc.DesistimientoService/Desistimiento"
)

// DesistimientoServiceClient is the client API for DesistimientoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DesistimientoServiceClient interface {
	Desistimiento(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type desistimientoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDesistimientoServiceClient(cc grpc.ClientConnInterface) DesistimientoServiceClient {
	return &desistimientoServiceClient{cc}
}

func (c *desistimientoServiceClient) Desistimiento(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, DesistimientoService_Desistimiento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesistimientoServiceServer is the server API for DesistimientoService service.
// All implementations must embed UnimplementedDesistimientoServiceServer
// for forward compatibility.
type DesistimientoServiceServer interface {
	Desistimiento(context.Context, *structpb.Struct) (*structpb.Struct, error)
	mustEmbedUnimplementedDesistimientoServiceServer()
}

// UnimplementedDesistimientoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesistimientoServiceServer struct{}

func (UnimplementedDesistimientoServiceServer) Desistimiento(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method Desistimiento not implemented")
}
func (UnimplementedDesistimientoServiceServer) mustEmbedUnimplementedDesistimientoServiceServer() {}
func (UnimplementedDesistimientoServiceServer) testEmbeddedByValue()                              {}

// UnsafeDesistimientoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesistimientoServiceServer will
// result in compilation errors.
type UnsafeDesistimientoServiceServer interface {
	mustEmbedUnimplementedDesistimientoServiceServer()
}

func RegisterDesistimientoServiceServer(s grpc.ServiceRegistrar, srv DesistimientoServiceServer) {
	// If the following call panics, it indicates UnimplementedDesistimientoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DesistimientoService_ServiceDesc, srv)
}

func _DesistimientoService_Desistimiento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesistimientoServiceServer).Desistimiento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesistimientoService_Desistimiento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesistimientoServiceServer).Desistimiento(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

// DesistimientoService_ServiceDesc is the grpc.ServiceDesc for DesistimientoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DesistimientoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apigrpc.DesistimientoService",
	HandlerType: (*DesistimientoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Desistimiento",
			Handler:    _DesistimientoService_Desistimiento_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/desistimiento.proto",
}
