// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/iva.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IvaService_Iva_FullMethodName = "/apigrpc.IvaService/Iva"
)

// IvaServiceClient is the client API for IvaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IvaServiceClient interface {
	Iva(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type ivaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIvaServiceClient(cc grpc.ClientConnInterface) IvaServiceClient {
	return &ivaServiceClient{cc}
}

func (c *ivaServiceClient) Iva(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, IvaService_Iva_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IvaServiceServer is the server API for IvaService service.
// All implementations must embed UnimplementedIvaServiceServer
// for forward compatibility.
type IvaServiceServer interface {
	Iva(context.Context, *structpb.Struct) (*structpb.Struct, error)
	mustEmbedUnimplementedIvaServiceServer()
}

// UnimplementedIvaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIvaServiceServer struct{}

func (UnimplementedIvaServiceServer) Iva(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method Iva not implemented")
}
func (UnimplementedIvaServiceServer) mustEmbedUnimplementedIvaServiceServer() {}
func (UnimplementedIvaServiceServer) testEmbeddedByValue()                    {}

// UnsafeIvaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IvaServiceServer will
// result in compilation errors.
type UnsafeIvaServiceServer interface {
	mustEmbedUnimplementedIvaServiceServer()
}

func RegisterIvaServiceServer(s grpc.ServiceRegistrar, srv IvaServiceServer) {
	// If the following call panics, it indicates UnimplementedIvaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IvaService_ServiceDesc, srv)
}

func _IvaService_Iva_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IvaServiceServer).Iva(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IvaService_Iva_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IvaServiceServer).Iva(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

// IvaService_ServiceDesc is the grpc.ServiceDesc for IvaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IvaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apigrpc.IvaService",
	HandlerType: (*IvaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Iva",
			Handler:    _IvaService_Iva_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/iva.proto",
}
