// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/service.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SIMPLIFICADOS_SIMPLIFICADOS_FullMethodName = "/apigrpc.SIMPLIFICADOS/SIMPLIFICADOS"
)

// SIMPLIFICADOSClient is the client API for SIMPLIFICADOS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SIMPLIFICADOSClient interface {
	SIMPLIFICADOS(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type sIMPLIFICADOSClient struct {
	cc grpc.ClientConnInterface
}

func NewSIMPLIFICADOSClient(cc grpc.ClientConnInterface) SIMPLIFICADOSClient {
	return &sIMPLIFICADOSClient{cc}
}

func (c *sIMPLIFICADOSClient) SIMPLIFICADOS(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, SIMPLIFICADOS_SIMPLIFICADOS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SIMPLIFICADOSServer is the server API for SIMPLIFICADOS service.
// All implementations must embed UnimplementedSIMPLIFICADOSServer
// for forward compatibility.
type SIMPLIFICADOSServer interface {
	SIMPLIFICADOS(context.Context, *structpb.Struct) (*structpb.Struct, error)
	mustEmbedUnimplementedSIMPLIFICADOSServer()
}

// UnimplementedSIMPLIFICADOSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSIMPLIFICADOSServer struct{}

func (UnimplementedSIMPLIFICADOSServer) SIMPLIFICADOS(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SIMPLIFICADOS not implemented")
}
func (UnimplementedSIMPLIFICADOSServer) mustEmbedUnimplementedSIMPLIFICADOSServer() {}
func (UnimplementedSIMPLIFICADOSServer) testEmbeddedByValue()                       {}

// UnsafeSIMPLIFICADOSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SIMPLIFICADOSServer will
// result in compilation errors.
type UnsafeSIMPLIFICADOSServer interface {
	mustEmbedUnimplementedSIMPLIFICADOSServer()
}

func RegisterSIMPLIFICADOSServer(s grpc.ServiceRegistrar, srv SIMPLIFICADOSServer) {
	// If the following call pancis, it indicates UnimplementedSIMPLIFICADOSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SIMPLIFICADOS_ServiceDesc, srv)
}

func _SIMPLIFICADOS_SIMPLIFICADOS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SIMPLIFICADOSServer).SIMPLIFICADOS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SIMPLIFICADOS_SIMPLIFICADOS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SIMPLIFICADOSServer).SIMPLIFICADOS(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

// SIMPLIFICADOS_ServiceDesc is the grpc.ServiceDesc for SIMPLIFICADOS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SIMPLIFICADOS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apigrpc.SIMPLIFICADOS",
	HandlerType: (*SIMPLIFICADOSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SIMPLIFICADOS",
			Handler:    _SIMPLIFICADOS_SIMPLIFICADOS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
