// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/service_Fracciones.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FraccionesService_Fracciones_FullMethodName = "/apigrpc.FraccionesService/Fracciones"
)

// FraccionesServiceClient is the client API for FraccionesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraccionesServiceClient interface {
	Fracciones(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type fraccionesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFraccionesServiceClient(cc grpc.ClientConnInterface) FraccionesServiceClient {
	return &fraccionesServiceClient{cc}
}

func (c *fraccionesServiceClient) Fracciones(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, FraccionesService_Fracciones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraccionesServiceServer is the server API for FraccionesService service.
// All implementations must embed UnimplementedFraccionesServiceServer
// for forward compatibility.
type FraccionesServiceServer interface {
	Fracciones(context.Context, *structpb.Struct) (*structpb.Struct, error)
	mustEmbedUnimplementedFraccionesServiceServer()
}

// UnimplementedFraccionesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFraccionesServiceServer struct{}

func (UnimplementedFraccionesServiceServer) Fracciones(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method Fracciones not implemented")
}
func (UnimplementedFraccionesServiceServer) mustEmbedUnimplementedFraccionesServiceServer() {}
func (UnimplementedFraccionesServiceServer) testEmbeddedByValue()                           {}

// UnsafeFraccionesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraccionesServiceServer will
// result in compilation errors.
type UnsafeFraccionesServiceServer interface {
	mustEmbedUnimplementedFraccionesServiceServer()
}

func RegisterFraccionesServiceServer(s grpc.ServiceRegistrar, srv FraccionesServiceServer) {
	// If the following call panics, it indicates UnimplementedFraccionesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FraccionesService_ServiceDesc, srv)
}

func _FraccionesService_Fracciones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraccionesServiceServer).Fracciones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraccionesService_Fracciones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraccionesServiceServer).Fracciones(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

// FraccionesService_ServiceDesc is the grpc.ServiceDesc for FraccionesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraccionesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apigrpc.FraccionesService",
	HandlerType: (*FraccionesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fracciones",
			Handler:    _FraccionesService_Fracciones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service_Fracciones.proto",
}
