// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sintactica.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_sintactica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sintactica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_sintactica_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_proto_sintactica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sintactica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_proto_sintactica_proto_rawDescGZIP(), []int{1}
}

func (x *FileResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_sintactica_proto protoreflect.FileDescriptor

const file_proto_sintactica_proto_rawDesc = "" +
	"\n" +
	"\x16proto/sintactica.proto\x1a\x1cgoogle/protobuf/struct.proto\"*\n" +
	"\vFileRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\";\n" +
	"\fFileResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data2;\n" +
	"\rFileProcessor\x12*\n" +
	"\vProcessFile\x12\f.FileRequest\x1a\r.FileResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_sintactica_proto_rawDescOnce sync.Once
	file_proto_sintactica_proto_rawDescData []byte
)

func file_proto_sintactica_proto_rawDescGZIP() []byte {
	file_proto_sintactica_proto_rawDescOnce.Do(func() {
		file_proto_sintactica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sintactica_proto_rawDesc), len(file_proto_sintactica_proto_rawDesc)))
	})
	return file_proto_sintactica_proto_rawDescData
}

var file_proto_sintactica_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sintactica_proto_goTypes = []any{
	(*FileRequest)(nil),     // 0: FileRequest
	(*FileResponse)(nil),    // 1: FileResponse
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_proto_sintactica_proto_depIdxs = []int32{
	2, // 0: FileResponse.data:type_name -> google.protobuf.Struct
	0, // 1: FileProcessor.ProcessFile:input_type -> FileRequest
	1, // 2: FileProcessor.ProcessFile:output_type -> FileResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_sintactica_proto_init() }
func file_proto_sintactica_proto_init() {
	if File_proto_sintactica_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sintactica_proto_rawDesc), len(file_proto_sintactica_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sintactica_proto_goTypes,
		DependencyIndexes: file_proto_sintactica_proto_depIdxs,
		MessageInfos:      file_proto_sintactica_proto_msgTypes,
	}.Build()
	File_proto_sintactica_proto = out.File
	file_proto_sintactica_proto_goTypes = nil
	file_proto_sintactica_proto_depIdxs = nil
}
