// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: api/grpc/TCambio.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TCambioService_TCambio_FullMethodName = "/apigrpc.TCambioService/TCambio"
)

// TCambioServiceClient is the client API for TCambioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TCambioServiceClient interface {
	TCambio(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type tCambioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTCambioServiceClient(cc grpc.ClientConnInterface) TCambioServiceClient {
	return &tCambioServiceClient{cc}
}

func (c *tCambioServiceClient) TCambio(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, TCambioService_TCambio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TCambioServiceServer is the server API for TCambioService service.
// All implementations must embed UnimplementedTCambioServiceServer
// for forward compatibility.
type TCambioServiceServer interface {
	TCambio(context.Context, *structpb.Struct) (*structpb.Struct, error)
	mustEmbedUnimplementedTCambioServiceServer()
}

// UnimplementedTCambioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTCambioServiceServer struct{}

func (UnimplementedTCambioServiceServer) TCambio(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Error(codes.Unimplemented, "method TCambio not implemented")
}
func (UnimplementedTCambioServiceServer) mustEmbedUnimplementedTCambioServiceServer() {}
func (UnimplementedTCambioServiceServer) testEmbeddedByValue()                        {}

// UnsafeTCambioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TCambioServiceServer will
// result in compilation errors.
type UnsafeTCambioServiceServer interface {
	mustEmbedUnimplementedTCambioServiceServer()
}

func RegisterTCambioServiceServer(s grpc.ServiceRegistrar, srv TCambioServiceServer) {
	// If the following call panics, it indicates UnimplementedTCambioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TCambioService_ServiceDesc, srv)
}

func _TCambioService_TCambio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TCambioServiceServer).TCambio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TCambioService_TCambio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TCambioServiceServer).TCambio(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

// TCambioService_ServiceDesc is the grpc.ServiceDesc for TCambioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TCambioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apigrpc.TCambioService",
	HandlerType: (*TCambioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TCambio",
			Handler:    _TCambioService_TCambio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/TCambio.proto",
}
